// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `fmt`, `from`, `from`, `source`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {
  Future<void> close();

  static Future<Client> connect({
    required String serverAddr,
    required String serverName,
    required String certPem,
  }) => RustLib.instance.api.crateApiHealthzClientConnect(
    serverAddr: serverAddr,
    serverName: serverName,
    certPem: certPem,
  );

  Future<HealthResponse> healthz();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientError>>
abstract class ClientError implements RustOpaqueInterface {}

class HealthResponse {
  final String status;
  final String version;

  const HealthResponse({required this.status, required this.version});

  @override
  int get hashCode => status.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthResponse &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          version == other.version;
}
